import type { Metadata } from 'next';
import { Blinker, Open_Sans } from 'next/font/google';
import './globals.css';

const blinker = Blinker({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-blinker',
});

const openSans = Open_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${blinker.variable} ${openSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
