import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';

// const myFontBlinker = localFont({
//   src: '',
//   display: 'swap',
//   variable: '--font-my-blinker',
// });

// const blinker = Blinker({
//   subsets: ['latin'],
//   weight: ['400', '800'],
//   variable: '--font-blinker',
// });

const openSans = Open_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700', '800'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.variable}`}>{children}</body>
    </html>
  );
}
